version: '3.8'

services:
  produto-db:
    image: postgres
    environment:
      POSTGRES_USER: produto_user
      POSTGRES_PASSWORD: produto_pass
      POSTGRES_DB: produto_db
    ports:
      - "5433:5432"

  usuario-db:
    image: postgres
    environment:
      POSTGRES_USER: usuario_user
      POSTGRES_PASSWORD: usuario_pass
      POSTGRES_DB: usuario_db
    ports:
      - "5434:5432"

  produto:
    build: ./produto
    ports:
      - "8081:8080"
    depends_on:
      - produto-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://produto-db:5432/produto_db
      SPRING_DATASOURCE_USERNAME: produto_user
      SPRING_DATASOURCE_PASSWORD: produto_pass

  usuario:
    build: ./usuario
    ports:
      - "8082:8080"
    depends_on:
      - usuario-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://usuario-db:5432/usuario_db
      SPRING_DATASOURCE_USERNAME: usuario_user
      SPRING_DATASOURCE_PASSWORD: usuario_pass
